name: Release CI

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: macos-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx6G -XX:MaxMetaspaceSize=4G"

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Test
        run: ./gradlew test

      - name: Lint
        run: ./gradlew lint

      - name: Detekt
        run: ./gradlew detekt
